name: Tests

on:
    push:
        branches: ["main"]
    pull_request:

permissions:
  packages: read
  # Note: from https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
  # > If you specify the access for any of these scopes, all of those that are not specified are set to none.

jobs:
    check-signoff:
        if: "github.event_name == 'pull_request'"
        uses: "matrix-org/backend-meta/.github/workflows/sign-off.yml@v2"

    tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Install
              run: yarn install

            - name: Build
              run: yarn build

            - name: Lint
              run: yarn lint ./src

            - name: Test
              run: yarn test

            - name: Docker Build
              run: docker build -t tardis .

            - name: Synapse Shim Build
              run: docker build -t synapse-shim ./shims/synapse

            - name: Synapse Shim Test
              run: |
                docker run -d -p 1234:1234 synapse-shim
                apt update && apt install -y jq
                wget -O websocat 'https://github.com/vi/websocat/releases/download/v1.14.0/websocat.x86_64-unknown-linux-musl'
                chmod u+x ./websocat
                ( echo '{"id":"9f2b4e90-8261-4988-952c-04741da2f98c","type":"resolve_state","data":{"state":[],"room_id":"!quickstart:tardis","room_version":"10","event":{"type":"m.room.create","state_key":"","sender":"@creator:tardis","auth_events":[],"prev_events":[],"content":{"creator":"@creator:tardis"},"event_id":"$rejaKriQdJnPoF0xEY9yqYU8Nt-jNnmD6ypuXY-0H14","origin_server_ts":1704067200000,"room_id":"!quickstart:tardis"}}}' | timeout 3 ./websocat --no-close --oneshot ws://localhost:1234 ) > resp.log || echo ''
                cat resp.log
                output=$(cat resp.log | jq -r .data.error)
                if [ -n "$output" ]; then
                  exit 1
